[package]
name = "simple_terminal"
version = "0.1.1"
authors = ["runner"]
edition = "2021"

[lib]
name = "simple_terminal"
path = "src/lib.rs"

[dependencies]
libc = "0.2.146"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
