[package]
name = "simple-terminal"
version = "0.1.0"
authors = ["runner"]
edition = "2021"

[lib]
name = "simple_terminal"
path = "src/lib.rs"

[dependencies]
libc

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html